const { exec } = require('child_process');
const path = require('path');
const fs = require('fs-extra');

/**
 * Transcribes audio file to text using Python's OpenAI Whisper
 * @param {string} audioPath - Path to the .wav file
 * @returns {Promise<string>} - Transcribed text
 */
async function transcribeAudio(audioPath) {
    return new Promise((resolve, reject) => {
        console.log(`[STT] Transcribing audio with Python Whisper: ${audioPath}`);
        
        // Command: whisper path/to/audio.wav --model base --output_format txt --output_dir path/to/dir
        const outputDir = path.dirname(audioPath);
        const fileName = path.basename(audioPath, '.wav');
        const txtFilePath = path.join(outputDir, `${fileName}.txt`);

        // Use '--language en' to skip detection and avoid charmap encoding errors on Windows
        const whisperPath = 'C:\\Users\\HP\\AppData\\Roaming\\Python\\Python313\\Scripts\\whisper.exe';
        const command = `"${whisperPath}" "${audioPath}" --model base --language en --output_format txt --output_dir "${outputDir}"`;

        exec(command, async (error, stdout, stderr) => {
            if (error) {
                console.error(`[STT] Whisper Exec Error: ${error.message}`);
                return reject(error);
            }

            try {
                if (fs.existsSync(txtFilePath)) {
                    const text = await fs.readFile(txtFilePath, 'utf8');
                    // Cleanup the .txt file generated by whisper
                    await fs.remove(txtFilePath).catch(() => {});
                    
                    // Cleanup other files whisper might generate (.json, .srt, .vtt, .tsv) if they exist
                    const formats = ['.json', '.srt', '.vtt', '.tsv'];
                    for (const fmt of formats) {
                        await fs.remove(path.join(outputDir, `${fileName}${fmt}`)).catch(() => {});
                    }

                    resolve(text.trim());
                } else {
                    // Clean up common meta-messages if they leaked into stdout
                    const cleanText = stdout.replace(/Detecting language.*?\n/g, '')
                                            .replace(/Detected language.*?\n/g, '')
                                            .replace(/UnicodeEncodeError.*?\n/g, '')
                                            .trim();
                    resolve(cleanText);
                }
            } catch (readErr) {
                reject(readErr);
            }
        });
    });
}

module.exports = {
    transcribeAudio
};
